### ISSUE TITLE
[1.12.2] Error when killAnimalGroups is enabled

### ISSUE THREAD

**Issue by LiskoSlayer63** [axle2005/ClearMob#22] opened 2018-02-16 05:22 UTC
Like the title says, everytime when ClearMob tries to clean the server [this](https://pastebin.com/mhPyEkt3) is printed to the console.

**ClearMob version:** 2.0.1
**SpongeForge version:** 2586-7.1.0
**Forge version:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by axle2005** [comment] 2018-02-16 11:20
Duplicate of #17

**Closed as completed by axle2005** 2018-02-16 11:20 UTC
Labels: duplicate
